### ISSUE TITLE
Hensara: subtitles feedback

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#115]
# Feedback

## Ep. 01

```
~ 11:43
公园内发生神秘爆炸!?
公園内發生神秘爆炸!?
```

From the wiki of the repo, the punctuation in the Chinese part here should be reversed? _(!? -> ?!)_

```
~ 12:08
别家的伙食吃的比我家好
別家的伙食吃的比我家好
```

_比我家好_ seems to be used to describe the action of  _eat_. _吃的 -> 吃得_ maybe better?

```
~ 13:53
也就吃的太寒酸 习惯不来
也就吃的太寒酸 習慣不來
```

I am not sure what _太寒酸_ is used to describe. Does it describe the action of _eating_, or does it describe the omitted _things to eat_? I think if it is the former, _得_ should be used, otherwise, _的_ should be used.

```
~ 18:28
你自己把名子提出来了 而且没人这么称呼你
你自己把名子提出來了 而且沒人這麼稱呼你
```

_名子 -> 名字_

## Ep. 02

```
~ 00:53
那就只能脚踏实地地四处打探
那就只能腳踏實地地四處打探
```

The second _地_ is not required and may be removed.

```
~ 03:28
独立保障机构：日本政府为了使贫困人口能够获得一定的自主生活能力的救助机构
獨立保障機構：日本政府為了使貧困人口能夠獲得一定的自主生活能力的救助機構
```

_为了/為了…设立的/設立的_ this sentence structure looks better.

```
~ 17:15
这个把全身都变得透明吗
這個把全身都變得透明嗎
```

It might look better if a _能_ could be added. _(这个能把全身/這個能把全身)_

```
~ 17:47
目标=调查对象
目標=調查對象
```

It would be great if you could add half-width spaces around the equal sign, consistent with the Japanese section below.

<details>
<summary>Preview</summary>

![](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/158490944/132b80e7-bfdd-4f5f-a21b-6a553219faf6)

</details>

```
~ 20:08
还不清楚汉字什么
還不清楚漢字什麼
```

It might look better if a _是_ could be added _(汉字是什么/漢字是什麼)_ or _-> 什么汉字/什麼漢字_

```
~ 20:40
```

Here _Kaburaya Sosuke_ says a word, but there are no subtitles.

<details>
<summary>Preview</summary>

![](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/158490944/72f5171e-11ad-4add-bce7-84a3ff907b90)

</details>

## Ep. 03

```
~ 15:56
岐阜烧鸡：用味增或者酱油做好料汁然后浇到鸡肉上，然后和蔬菜一起烤制。
岐阜燒雞：用味噌或者醬油做好料汁然後澆到雞肉上，然後和蔬菜一起烤製。
```

_味增_ -> _味噌_ _CHT_ looks fine.

```
~ 15:58
我知道了 酱汁的味道很好的渗进了肉里面
我知道了 醬汁的味道很好的滲進了肉裡面
```

_很好的_ -> _很好地_ maybe better?

```
~ 19:21
我明明刚才才受到你的祝福
我明明剛才才受到你的祝福
```

If swap the _明明_ and _刚才/剛才_, it will be more consistent with language habits.

## Ep. 04

```
~ 08:40
才意识到他其实比书中写得要厉害很多
才意識到他其實比書中寫得要厲害很多
```

_写得/寫得_ -> _写的/寫的_ I think it is more appropriate.

```
~ 12:21
```

Consider translating it?

<details>
<summary>Preview</summary>

![](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/158490944/a15669d0-f3a8-467b-a652-5622d9b556a0)

</details>

```
~ 15:03
友奈和他妈妈才得救了
友奈和他媽媽才得救了
```

_Yuna_ is a GIRL lol. _(他 -> 她)_

```
~ 21:12
原来是在原来的世界啊
原來是在原來的世界啊
```

The two _原来/原來_ are a bit awkward to pronounce. Could you consider another form of translation?

## Ep. 05

```
~ 03:07
不行 光想这些没有的也不是办法
不行 光想這些沒有的也不是辦法
```

Other translations I can personally think of: _光想这些有的没的_ or _光想这些没用的_

```
~ 06:37
身体好不容易才暖和起来的吗
这一泡不就又冷了
身體好不容易才暖和起來的嗎
這一泡不就又冷了
```

My advice:

1. Move _吗/嗎_ to the end of the second sentence
2. Or, change _吗/嗎_ to _嘛_

```
~ 20:02
一旦大量采购 商品就会很快不在市场上流通
一旦大量採購 商品就會很快不在市場上流通
```

If swap the _就会/就會_ and _很快_, it will be more consistent with language habits.

## Ep. 06

```
~ 05:26
好……好的
```

You can just leave an ellipsis. _(好…好的)_

```
~ 16:15
成员间的不和已经反应到了音乐上
成員間的不和已經反應到了音樂上
```

_反应/反應_ -> _反映_ is more accurate.

```
~ 17:13
多亏望爱阁下介绍给在下吉他老师和退役乐队成员
多虧望愛閣下介紹給在下吉他老師和退役樂隊成員
```

If swap the _介绍/介紹_ and _给在下/給在下_, it will be more consistent with language habits.

## Ep. 07

```
~ 16:21
第一名5号飞騨牛珍豪驰
第一名5號飛驒牛珍豪馳
~ 20:31
惣助 今晚就吃飞驒牛肉吧
惣助 今晚就吃飛驒牛肉吧
~ 22:06
可口的飞騨牛肉
可口的飛驒牛肉
```

In *CHS*, *騨* appears three times, but one of them is different from the other two.

## Ep. 08

```
~ 03:07
在我高中的时候 曾和一位年长的女性犯下的一夜之错
在我高中的時候 曾和一位年長的女性犯下的一夜之錯
```

I suggest changing the last *的* to *了* or removing it.

```
~ 09:26
就算你推荐的电影烂的不忍直视
就算你推薦的電影爛的不忍直視
```

*烂的/爛的* -> *烂得/爛得* maybe better?

```
~ 14:40
今天原来是准备决定乐队的名称的
今天原來是準備決定樂隊的名稱的
```

**(OPTIONAL)** I understand what this sentence means. But from the sense of language, maybe it would be more appropriate to change *原来/原來* to *原本*?

## Ep. 09

```
~ 06:46
啊！？
```

Should we swap the two punctuation marks and change them to half-width form?

> 简体中文中连用感叹号与问号时，应为 `?!`，注意与日文的符号顺序相反

```
~ 12:46
真的什么什么事都没发生吗
真的什麼什麼事都沒發生嗎
```

I listened to it several times and I could not quite understand why there were two *什么/什麼*. Maybe it was a typo?

## Ep. 10

```
~ 00:44
日语自称较为复杂，后文出现的warawa,boku,watashi
都是日语自称的方式,用于不同场合和不同说话人。
日語自稱較為複雜，後文出現的warawa,boku,watashi
都是日語自稱的方式,用於不同場合和不同說話人。
```

The first comma in the first line is full-width, while the comma in the second line is half-width. The actual effect looks a bit strange.

<details>
<summary>Preview</summary>

![](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/158490944/10e9d0a6-7620-43ae-9b93-0a884815f1ca)

![](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/158490944/95d792ed-074a-4232-b979-019014cf3c30)

</details>

```
~ 10:15
难到说 惣助…你做了吗？
難到說 惣助…你做了嗎？
```

*到* -> *道*

```
~ 10:26
莎拉其实是我的孩子
莎拉其實是我的孩子
```

*莎* -> *沙*

```
~ 12:19
他也会想要人能够在家庭事物上帮助他
他也會想要人能夠在家庭事物上幫助他
```

I suggest changing *人* to *有人*.

```
~ 14:43
你要找的话说不定能很快就找到结婚对象哦
你要找的話說不定能很快就找到結婚對象哦
```

*能很快就* -> *很快就能*

```
~ 18:41
然后自然地装出一份天真无邪的而感觉
然後自然地裝出一份天真無邪的而感覺
```

This *而* seems redundant.

```
~ 19:10
但是我从来没有做饭过啊
但是我從來沒有做過飯啊
```

*做饭过* -> *做过饭*. The *CHT* looks fine.

## Ep. 11

```
~ 03:26
公主大人 请让这个人偶代替在下陪在身边吧
公主大人 請讓這個人偶代替在下陪在身邊吧
```

I suggest adding a subject to the second half of the sentence. Like *代替在下陪在你身边/代替在下陪在你身邊*.

```
~ 10:52
顺带一提 你觉得那个最好吃？
順帶一提 你覺得那個最好吃？
```

*那* -> *哪*

```
~ 11:43
哎 虾刺身吃还蛮好吃
哎 蝦刺身吃還蠻好吃
```

I guess *身* -> *生*

```
~ 17:15
吸取这次的失败的教训 让我们挑战第二次吧
吸取這次的失敗的教訓 讓我們挑戰第二次吧
```

I suggest removing the second *的*, because feels redundant when reading. *(这次失败的教训/這次失敗的教訓)*

```
~ 17:19
没问题 律师老师
沒問題 律師老師
```

It is written as *律师小姐/律師小姐* elsewhere, but it is written as *律师老师/律師老師* here.

```
~ 18:02
但是厌倦了接连不断的诽谤和为金钱是图而失踪
但是厭倦了接連不斷的誹謗和為金錢是圖而失蹤
```

*为/為* -> *唯*

```
~ 19:07
现在似乎在一个成为世界布兰奇山家族的邪教团体工作
現在似乎在一個成為世界布蘭奇山家族的邪教團體工作
```

*成为/成為* -> *称为/稱為*

```
~ 23:51
希望能和喜欢的人交往…不对。
可以的话希望能和喜欢的人结婚。
为此首先需要一次约会，
不首先应该是牵手吗……？
…这么羞耻的愿望
真不想被他人看到呀…
爱崎布兰达
希望能和喜歡的人交往…不對。
可以的話希望能和喜歡的人結婚。
為此首先需要一次約會，
不首先應該是牽手嗎……？
…這麼羞恥的願望
真不想被他人看到呀…
愛崎布蘭達
```

Of the four ellipsis, the second one has six dots and the others have three dots. Not sure if this was intentional, so I am mentioning it.

<details>
<summary>Preview</summary>

![](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/158490944/6ff28fd3-bb63-45de-a358-1337e644e1f7)

![](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/158490944/9f3a4d05-2eb3-4906-90c9-9f2eab7643c8)

</details>

## Ep. 12

```
~ 02:55
之后就只要送出去就好了
之後就只要送出去就好了
```

The two *就* sound a bit redundant, so I suggest removing the first one.

```
~ 10:41
今后有得是机会
今後有得是機會
```

*得* -> *的*

```
~ 10:51
初次见面 我是GIFT 唱片的土田智也
初次見面 我是GIFT 唱片的土田智也
~ 20:41
刚刚宣布将作为Gift Records旗下乐队主流出道
剛剛宣布將作為Gift Records旗下樂隊主流出道
```

1. In the first subtitle, I felt that the space between *GIFT* and *唱片* was unnecessary (it looked a bit weird).
2. Inconsistent translation

```
~ 11:47
可为什么连家长们都在这么激动
但為什麼連家長們都在這麼激動
```

*在* is not required and is recommended to be removed.

```
~ 12:30
草薙沙罗大人莅临了这座泽良小学
草薙沙羅大人蒞臨了這座澤良小學
~ 13:31
对你们来说 我可以放心地把这所学校托付给你们了
對你們來說 我可以放心地把這所學校託付給你們了
```

The first sentence uses *这座/這座* in the subtitles, and the second sentence uses *这所/這所*. Maybe the wording can be unified? *(Or maybe the original conversation had a different meaning but I do not know)*

```
~ 15:22
沙罗大人喜欢什么类型得人呀
沙羅大人喜歡什麼類型得人呀
```

*得* -> *的*

```
~ 20:36
嫌疑人所属乐队救世GRASSHOPPER于在昨日举行的公演上
嫌疑人所屬樂隊救世GRASSHOPPER於在昨日舉行的公演上
```

The semantics of *于/於* and *在* are redundant, so it is recommended to keep only one of them.

```
~ 04:48
就一直做个挣扎为生的烦人家伙吧
就一直做個掙扎為生的煩人傢伙吧
~ 22:55
就一直作个挣扎为生的烦人家伙吧
就一直作個掙扎為生的煩人傢伙吧
```

This issue has been reported before. The opening part here is consistent with episodes 07 to 11, but the ending part is wrong again.

<details>
<summary>Preview</summary>

![](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/158490944/4ab5e037-4d2d-4731-b592-3ea369427757)

![](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/158490944/4f85e6e3-ed9f-4488-837e-9e98c0a40bce)

![](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/158490944/a44e9d04-3e8f-41e4-a96a-db72d85c6829)

![](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/158490944/dbb8ada7-d4a4-4e02-b154-d2f7f5224e5a)

</details>

### Lyrics

In the lyrics of the opening section:

```
就一直作个挣扎为生的烦人家伙吧
就一直作個掙扎為生的煩人傢伙吧
```

_作_ -> _做_ maybe it is more in line with language habits?

### CHARACTER FILE

Some _CHARACTER FILE_ in ep. 02 translate name, occupation, and age, but some _CHARACTER FILE_ in ep. 01 do not translate age.

<details>
<summary>Preview</summary>

![](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/158490944/ee930a73-b8ed-480b-9bbb-f579843ee4d4)

![](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/158490944/0b6ec2de-3e69-42f3-8d7a-2b316712825c)

</details>

### Translation format for full name mentions in dialogue subtitles

Sometimes when the full name of a character is mentioned, some translations include a half-width space in the middle, and some do not. Below as an example. If you have time you can unify it.

<details>
<summary>Preview</summary>

_我的名字叫<ins>闺 春花</ins>_
![](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/158490944/80cefb47-3a84-4117-a782-43494bc15c9b)

_记得你是<ins>皆神望爱</ins>阁下吧_
![](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/158490944/b0660f30-bb6b-4627-a69b-56903b68d931)

</details>

### <s>做…曲 or 作…曲 **(OPTIONAL)**</s>

> …做出…歌曲…
> …做出…曲子…

<s>For statements similar to the above structure, using *作* seems more customary *(作曲)*.</s>

### Translation of *Minakami Noa* in *CHS*

In some episodes of *CHS* (focusing on ep. 05 and ep. 06), *Noa’s* translation incorrectly uses traditional Chinese characters.

<details>
<summary>Preview</summary>

*Ep. 05 ~ 23:55*
![](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/158490944/4026df75-8f9e-418d-ac53-e26e21534d61)

*Ep. 06 ~ 18:14*
![](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/158490944/ba8e3d98-a33d-4d11-9672-3f984499b898)

*Ep. 06 ~ 18:19*
![](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/158490944/9cb0dd89-7462-4297-b336-d3016e1fafab)

</details>

### Some of the same dialogues are translated differently

This usually happens between the preview of the next episode and the second episode. Here is an example, but there are probably others like it.

Not sure if this was intentional, so mentioning it.

<details>
<summary>Preview</summary>

*Ep. 08 ~ 23:47*
![](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/158490944/9475c347-38cb-4a35-83c9-14373a4d33b3)

*Ep. 09 ~ 12:55*
![](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/158490944/cc3a958a-d1d4-44ee-9358-aaa7b0b79f47)

*Ep. 08 ~ 24:07*
![](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/158490944/47ae2998-3597-4aa3-bda3-028fd2f5fd22)

*Ep. 09 ~ 12:46*
![](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/158490944/af5e7023-c221-42a6-ac9a-bd5fe0f752fb)

</details>

# Sources

_Unbatch releases._

```
[Nekomoe kissaten][Henjin no Salad Bowl][01][1080p][CHS].mp4
[Nekomoe kissaten][Henjin no Salad Bowl][01][1080p][CHT].mp4
[Nekomoe kissaten][Henjin no Salad Bowl][02][1080p][CHS].mp4
[Nekomoe kissaten][Henjin no Salad Bowl][02][1080p][CHT].mp4
[Nekomoe kissaten][Henjin no Salad Bowl][03][1080p][CHS].mp4
[Nekomoe kissaten][Henjin no Salad Bowl][03][1080p][CHT].mp4
[Nekomoe kissaten][Henjin no Salad Bowl][04][1080p][CHS].mp4
[Nekomoe kissaten][Henjin no Salad Bowl][04][1080p][CHT].mp4
[Nekomoe kissaten][Henjin no Salad Bowl][05][1080p][CHS].mp4
[Nekomoe kissaten][Henjin no Salad Bowl][05][1080p][CHT].mp4
[Nekomoe kissaten][Henjin no Salad Bowl][06][1080p][CHS].mp4
[Nekomoe kissaten][Henjin no Salad Bowl][06][1080p][CHT].mp4
[Nekomoe kissaten][Henjin no Salad Bowl][07][1080p][CHS].mp4
[Nekomoe kissaten][Henjin no Salad Bowl][07][1080p][CHT].mp4
[Nekomoe kissaten][Henjin no Salad Bowl][08][1080p][CHS].mp4
[Nekomoe kissaten][Henjin no Salad Bowl][08][1080p][CHT].mp4
[Nekomoe kissaten][Henjin no Salad Bowl][09][1080p][CHS].mp4
[Nekomoe kissaten][Henjin no Salad Bowl][09][1080p][CHT].mp4
[Nekomoe kissaten][Henjin no Salad Bowl][10][1080p][CHS].mp4
[Nekomoe kissaten][Henjin no Salad Bowl][10][1080p][CHT].mp4
[Nekomoe kissaten][Henjin no Salad Bowl][11][1080p][CHS].mp4
[Nekomoe kissaten][Henjin no Salad Bowl][11][1080p][CHT].mp4
[Nekomoe kissaten][Henjin no Salad Bowl][12][1080p][CHS].mp4
[Nekomoe kissaten][Henjin no Salad Bowl][12][1080p][CHT].mp4
```

**Comment by NMRingOfTime** [comment]
Thanks for your detailed feedback. We are now working on our batched release and your timely feedback helps a lot. We will fix them in our batched release.
