### ISSUE TITLE
LOVE_FLOPS: about web -> bd

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#121]
About some months ago, I made some relevant adjustments. I thought I would be able to complete and create a PR soon, but unfortunately the work has been stalled for various reasons. I have pretty much finished it recently and just need to do a few more checks before it available for review.

I used the adjusted subtitles to test several different BDRip, and they were all displayed accurately, so I initially think that the adjusted subtitles can be adapted to future BDRip of VCB-Studio.

However, I am not sure if your team is already working on it, so I did not create a PR without permission. If you welcome my PR, I can create it.

_By the way, a digression. During my time using GitHub, I have been constantly reflecting on what I say and do while submitting contributions. During this process, I learned a lot, and also corrected some previous misunderstandings. I have been following your team for a long time, and the subtitles on one of your team’s projects was an opportunity for me to start following the anime community, also thank you for all your team’s efforts in subtitles, I have benefited a lot from it. If nothing unexpected happens, I will continue to be active for some time to come. If I don’t do well enough or make some mistakes, please point them out and please bear with me, I will try my best to cooperate._

**Comment by MIRIMIRIM** [comment]
*LOVE FLOPS* is already on the plan list, and proofreader may make some adjustments, so PR may not be necessary.

Welcome to continue making contributions!
