### ISSUE TITLE
关于girls band cry第七集第八分钟处翻译的一点个人看法

### ISSUE THREAD

**Issue by uselesso** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#127]
8分07秒那里”如果“后面多加一个主语你是不是比较好？改成“如果你当时选择不再追究霸凌者的责任”，第一次看还以为是学校不再追究霸凌者的责任就会理亏，和上下文联系不起来，没搞明白。最近才开始追番，如果有做的不对的还请轻喷。

**Comment by Ronny-zzl** [comment]
https://github.com/Nekomoekissaten-SUB/sub_backup/commit/a997a8f4f3fd8f8feb166cdd6e1dff7d1f80e98b

**Comment by uselesso** [comment]
请问你发的这个链接是什么，为什么404无法访问。

**Comment by uselesso** [comment]
> https://github.com/Nekomoekissaten-SUB/sub_backup/commit/a997a8f4f3fd8f8feb166cdd6e1dff7d1f80e98b

请问你发的链接是什么，为什么404无法访问。

**Comment by uselesso** [comment]
> https://github.com/Nekomoekissaten-SUB/sub_backup/commit/a997a8f4f3fd8f8feb166cdd6e1dff7d1f80e98b

请问你发的链接是什么，为什么404无法访问？
