### ISSUE TITLE
Urusei-Yatsura (2022)


### ISSUE THREAD

**Issue by Moscow1991** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#130]
Urusei-Yatsura (2022)
Feedback
S2 Ep. 17
~16: 07
先给你嗯三分钟
先给你们三分钟

你嗯→你们

**Comment by MIRIMIRIM** [comment]
https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Storage/blob/506e5597f0c099131cd19fa53681e9df2156878c/Urusei_Yatsura/Subs/%5BNekomoe%20kissaten%5D%20Urusei%20Yatsura%202022%20%5B40%5D%5BWeb%5D.JPSC.ass#L680
