### ISSUE TITLE
你会添加Tonikaku Kawaii字幕源文件吗？

### ISSUE THREAD

**Issue by jp-parachute** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#14]
1-9集的源文件可以在网上找到。GITHUB上没有。你们会发布吗？

(我使用谷歌翻译。我很抱歉。)

**Comment by MIRIMIRIM** [comment]
https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/commit/7eca234913c7499a80b53244e7010786cf3a6b9c
