### ISSUE TITLE
超自然武装当哒当第1集，音频单声道问题

### ISSUE THREAD

**Issue by Souddt** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#142]
目前胆大党第一集的音频好像有问题，只有单声道，听着怪怪的
我猜咱喵萌是用的CR源吧，目前胆大党第一集的CR源都是单声道（PS：CR的锅）
建议后面可以换其他源
![image](https://github.com/user-attachments/assets/3cd695f1-a7d3-4486-ae6c-5b51380cfa41)
![image](https://github.com/user-attachments/assets/e5578df8-1224-433c-9ea2-0eee5079c438)
![image](https://github.com/user-attachments/assets/66c09399-57c4-4611-b884-4d143ab5866d)

**Comment by MIRIMIRIM** [comment]
CR 已经在第二集开始修复了音频问题，第一集会在合集时修复音频
