### ISSUE TITLE
败犬的第5集是不是漏掉了

### ISSUE THREAD

**Issue by Traserve** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#143]
没找到第5集的字幕

**Comment by 3gf8jv4dv** [comment]
05-07 in the same torrent. dmhy has this.
05-07 在同一个种子里。dmhy 是有的。

**Comment by jinhang1997** [comment]
败犬第 5 集简繁都发了的，和 06.07 在一个种子里。
没有发外挂字幕，内封字幕版由 LoliHouse 发布，也是发了的。
