### ISSUE TITLE
关于地球的运动 01-02 内封

### ISSUE THREAD

**Issue by WingRises** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#145]
文件：
[Nekomoe kissaten][Chi. Chikyuu no Undou ni Tsuite][01][WebRip 1080p HEVC-10bit AAC ASSx2]
[Nekomoe kissaten][Chi. Chikyuu no Undou ni Tsuite][02][WebRip 1080p HEVC-10bit AAC ASSx2]

问题：
进行了子集化操作，但附带的ASS字幕 字体名 未处理！

结果：
播放时，字体不会加载！呈现无子集化的效果！

**Comment by MIRIMIRIM** [comment]
后续会重发
