### ISSUE TITLE
[青箱 / Ao no Hako / Blue Box][04]字幕错误

### ISSUE THREAD

**Issue by jyt429** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#147]
青箱 04注释字幕部分少{
![屏幕截图 2024-10-21 162102](https://github.com/user-attachments/assets/8b5cc108-76c4-4d4b-a6ac-84ada0ee271f)

**Comment by jyt429** [comment]
内嵌字幕也有错误
![屏幕截图 2024-10-21 162604](https://github.com/user-attachments/assets/dc21b5cb-3f0b-48f0-920e-e5ddb717c8f8)

**Comment by MIRIMIRIM** [comment]
已经发布 v2
