### ISSUE TITLE
乱马1/2第8集和第1集无法下载的问题

### ISSUE THREAD

**Issue by keKe-116** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#160]
蜜柑或者acg的磁力链都没有办法下载其他集数都正常，请问是什么原因呢？

**Comment by MIRIMIRIM** [comment]
不知道，试试种子

**Comment by keKe-116** [comment]
![image](https://github.com/user-attachments/assets/a7dcb085-cd01-418f-90bc-0dfbb3a53c55)
![image](https://github.com/user-attachments/assets/d3682bab-90ed-4c43-b861-347ac6042776)
![image](https://github.com/user-attachments/assets/8140b196-88bd-498c-a99d-092e4d50981d)

好奇怪 track没一个工作的，而且没有种子
