### ISSUE TITLE
请问歌剧少女是否还会继续制作

### ISSUE THREAD

**Issue by Hare-W** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#24]
目前10月20日，贵组有10集内封字幕资源，请问后续3集是否还会继续制作，或者是否会出外挂字幕，谢谢

**Comment by MIRIMIRIM** [comment]
https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-MIR-Subs/commit/416aab62b9f044e923e86c6359dbf29cd690f2db
