### ISSUE TITLE
SAKUGAN

### ISSUE THREAD

**Issue by takua624** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#26]
您好，感謝貴組辛苦製作字幕！
請問貴組有否打算繼續製作遭到B站獨播的SAKUGAN呢？

**Comment by MIRIMIRIM** [comment]
https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-MIR-Subs/commit/7627160f4c8c9a887a3ea2919bf911ef665cd222
