### ISSUE TITLE
Where i can get japanese SoftSubtitle for Akebi-chan no Sailor-fuku

### ISSUE THREAD

**Issue by YinnVI** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#27]
Where i can get japanese Soft Subtitle for Akebi-chan no Sailor-fuku

thanks before, english please

**Comment by MIRIMIRIM** [comment]
Now, our *Akebi-chan* subtitles’ japanese part is written by translators according to heard japanese dub, we don’t have plan add updating subtitles to github repos.

And *Akebi-chan* will air at Japan broadcasting station AT-X when 2 days later than the premiere day, it will support japanese soft subtitles, you can try to get these.

**Comment by MIRIMIRIM** [comment]
This is Japanese subtitles from AT-X

[明日ちゃんのセーラー服_jpn_AT-X.zip](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/files/8656087/_jpn_AT-X.zip)
