### ISSUE TITLE
部分Update Done的番一直没有合集流出

### ISSUE THREAD

**Issue by xylonx** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#28]
### question
项目表中部分番剧为Update Done状态，持续跟踪一两个月后，一直没有发现TV collection / BD collection流出，请问他们是否已经被弃坑，或者是仍在继续制作中？
### reason
我的番主要是在nyaa上下载的raw因此需要外挂字幕的支持。

**Comment by MIRIMIRIM** [comment]
分集更新完成（Update Done）的项目一般在等待校对和后期的修正，如翻译、样式、时间轴等，等修正完成后便会合集并上传外挂字幕。
