### ISSUE TITLE
请问能否发布基于摇曳露营字幕制作的diy原盘

### ISSUE THREAD

**Issue by b804159827** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#29]
制作了基于此https://github.com/Nekomoekissaten-SUB/Yuru-Camp 字幕的BDdiy作品，字幕修改了时间轴匹配bd版本，更改了字幕排版使其更美观，主页说明了不能发布基于此字幕的加流重灌作品。纯个人玩家，无任何利益交割，希望在此能得到使用授权，如能通过表示由衷感谢。

**Comment by b804159827** [comment]
打算发在u2和tsdm。

**Comment by MIRIMIRIM** [comment]
公开的非可修改文本的二次发布不允许对字幕内容（如翻译及样式）的修改，若有需求还望留作自用。

**Comment by b804159827** [comment]
> 公开的非可修改文本的二次发布不允许对字幕内容（如翻译及样式）的修改，若有需求还望留作自用。

谢谢回复，那也就是说调轴匹配bd可以，其他一切不更改就行了吧。

**Comment by MIRIMIRIM** [comment]
> > 公开的非可修改文本的二次发布不允许对字幕内容（如翻译及样式）的修改，若有需求还望留作自用。
> 
> 谢谢回复，那也就是说调轴匹配bd可以，其他一切不更改就行了吧。

能确保未对字幕内容（如翻译及样式）进行修改是可以的。

仅调轴后的字幕进行二次发布，对此持中立态度（不支持也不会反对），但推荐使用可编辑的文本形式。

对于会使用 PGS 图形字幕的 BDDIY：
1. 必须保证字幕渲染的正确性（如正确渲染的字体和字幕特效标签），允许可以接受的 VSFilter 与 libass 渲染不同导致的偏差
2. 推荐在发布的同时附带一份图形化时使用的文本字幕（不限于在发布的本体当中）
3. 必须要注明字幕原始来源（如主楼贴出的 Github 地址）

**Comment by b804159827** [comment]
明白了，非常感谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nekomoekissaten-SUB/Nekomoekissaten-Subs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月9日(星期六) 下午2:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nekomoekissaten-SUB/Nekomoekissaten-Subs] 请问能否发布基于摇曳露营字幕制作的diy原盘 (Issue #29)





   
公开的非可修改文本的二次发布不允许对字幕内容（如翻译及样式）的修改，若有需求还望留作自用。
  
谢谢回复，那也就是说调轴匹配bd可以，其他一切不更改就行了吧。
  
能确保未对字幕内容（如翻译及样式）进行修改是可以的。
 
仅调轴后的字幕进行二次发布，对此持中立态度（不支持也不会反对），但推荐使用可编辑的文本形式。
 
对于会使用 PGS 图形字幕的 BDDIY：
  
必须保证字幕渲染的正确性（如正确渲染的字体和字幕特效标签），允许可以接受的 VSFilter 与 libass 渲染不同导致的偏差
 
推荐在发布的同时附带一份图形化时使用的文本字幕（不限于在发布的本体当中）
 
必须要注明字幕原始来源（如主楼贴出的 Github 地址）
