### ISSUE TITLE
整理的表单很清晰，可我还是不知道哪里下载啊。

### ISSUE THREAD

**Issue by dyingway** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#30]
我已经仔细阅读了说明。我现在要下Ya Boy Kongming，但我发现我在页面里面找不到哪里可以下。git down好像也没有也下不了。

另外不知道能不能和sonarr或jellyfin结合。

谢谢解答。

**Comment by MIRIMIRIM** [comment]
一般是合集后才会把字幕传到 GitHub 上，同时会在 Subs Link 中给出对应链接。孔明这部目前还没有。

「和sonarr或jellyfin结合」是指的怎么结合？

**Comment by dyingway** [comment]
sonarr找到片源然后传送给BT客户端下载，然后sonarr导回jellyfin的狙击磁盘位置。jellyfin回家就能播放了。中文字幕一直没有好的解决办法。应该是有爱的字幕组各自为政的关系。
抱歉，前面github没通知有回复。

**Comment by acbetter** [comment]
这和本项目有啥关系。。。请尽量提出有意义的问题

**Comment by dyingway** [comment]
> 这和本项目有啥关系。。。请尽量提出有意义的问题

因为read me写着下载链接，但我找不到呀，类似找不到说明书里说的内容所以来问下，然后被告知说明书没写有些内容这里没有，只有清单。

**Comment by acbetter** [comment]
可以 close issue 了。。。
