### ISSUE TITLE
莉可丽丝ep1 字幕勘误

### ISSUE THREAD

**Issue by Acylation** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#33]
简体中文1080p，15'16''，”燃气爆炸世界的大楼“，应为”燃气爆炸事件的大楼“？
供参考

另，「食べモグ」译作大众点评有点摸不着头脑，能否加个注释？如neta tabelog这样？

**Comment by MIRIMIRIM** [comment]
第一处是打错字了，第二处会考虑下加注释。
