### ISSUE TITLE
已打包的字幕合集文件，在git代码库中找不到对应文件

### ISSUE THREAD

**Issue by project1188** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#37]
从提交历史看，字幕制作完成并发布到releases区后，会把git库中的字幕文件清理掉，但是releases中的字幕又无法同步到本地去，这样就多了一道下载的步骤，所以想问一下是否有可能在git库中继续保留这些打包好的字幕文件？

**Comment by MIRIMIRIM** [comment]
这个问题，之前在你对 Yuru-Camp 提交的 PR 中回答过，可能我把 repo 转 private 太快，你没有看到，下面是我当初的回答：

>打包好的字幕不再在 git 中保留的原因除去无法 diff 之外，还考虑到了 repo 体积可能过大会导致不便。按目前的计划，如果文本字幕本身不会过大均会在 repo 中保留一份的同时打包发布 release，否则只会打包上传到 release。如果想批量下载 release 下的文件，可以考虑通过 GitHub 的 API 获取下载地址并下载，比如 [https://api.github.com/repos/Nekomoekissaten-SUB/Nekomoekissaten-poi-Subs/releases](https://api.github.com/repos/Nekomoekissaten-SUB/Nekomoekissaten-poi-Subs/releases%E3%80%82) 。

由于大多数字幕体积过大是因为特效，就算本身不会很大，在重复 24 遍后总体积也会很可观。所以我尝试在 git 中保留不含特效的字幕文件、特效文件、合并两者的标记文件，在 release 中提供合并后的完整文件打包，从而在尽量保留 git 内字幕文件的前提下缩小总体积，比如 *[RPG Fudousan](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-MIR-Subs/tree/master/RPG_Fudousan)* 就采用了这种方式。

他人和古旧的字幕暂时还没有好的解决办法，如果造成了不便，还望谅解。

**Comment by project1188** [comment]
明白了，感谢解答
