### ISSUE TITLE
从花园下载的莉可丽丝内封字幕的第2集op部分没有字幕。

### ISSUE THREAD

**Issue by shrfqi** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#40]
从第3集开始之后的都有字幕，不知道字幕组方不方便再更新一版呢？

**Comment by Ronny-zzl** [comment]
会发合集

**Comment by shrfqi** [comment]
好的

**Comment by shrfqi** [comment]
还有字幕也该统一一下 左边第1集右边第5集
![image](https://user-images.githubusercontent.com/114376908/192212096-c6e1e94c-6bcc-409a-8c17-ccc8052b3b6d.png)
