### ISSUE TITLE
女神的露天咖啡厅 不再进行更新了吗?

### ISSUE THREAD

**Issue by fgr178707** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#47]
![image](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/109357981/9a5b0be5-cfa1-4959-b983-fc8c8daf7d6d)

**Comment by MIRIMIRIM** [comment]
https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-kin-Subs/commit/4e58e73f47fa2ceb50449501b31915c7cefac664
