### ISSUE TITLE
SYNDUALITY EP06 错字

### ISSUE THREAD

**Issue by sommio** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#62]
「0:19:15.79,0:19:18.06,Dial_CH,,0,0,0,,**呈**什么英雄」->「0:19:15.79,0:19:18.06,Dial_CH,,0,0,0,,**逞**什么英雄」

**Comment by vxzms** [comment]
ok，会在合集中修正

**Comment by MIRIMIRIM** [comment]
ok，会在合集中修正
