### ISSUE TITLE
异世界舅舅bd字幕链接失效

### ISSUE THREAD

**Issue by Lemonink96** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#64]
https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Storage/Isekai_Ojisan
打开这个链接会404 not found
![image](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/79908937/9fb2e7eb-1bcc-4247-8164-7b1df9ef7f4d)

**Comment by MIRIMIRIM** [comment]
已修，https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Storage/tree/master/Isekai_Ojisan

**Comment by Lemonink96** [comment]
Thanks for reply ：）
