### ISSUE TITLE
贵组今后还会继续在蜜柑计划上发布熟肉吗

### ISSUE THREAD

**Issue by SanaeMio** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#66]
观察到贵组自2023/11/22后就没有再往蜜柑计划上发布新番了（但dmhy有在更新），想问下今后是不再往蜜柑计划上发布熟肉了，还是因为什么原因只是临时暂停，谢谢

**Comment by MIRIMIRIM** [comment]
你好，敝组固定的发布站是动漫花园（dmhy）、Nyaa、acg.rip，除了发布时的站点宕机一般都会发。萌番组偶尔会发，蜜柑计划上都是从其他 BT 站同步的，不知道它同步的哪个站所以无法解答这个问题。

**Comment by Ronny-zzl** [comment]
我们并不在蜜柑计划上发布。
蜜柑计划依靠采集其他bt发布网站的数据维持内容，所以你应该询问蜜柑的管理员为何没有搜刮到你所说的资源。

**Comment by SanaeMio** [comment]
明白了，谢谢解答！
