### ISSUE TITLE
请问还有更新僵尸百分百最后 3 集字幕的计划吗

### ISSUE THREAD

**Issue by Robotxm** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#69]
这两天整理 NAS 上的资源，发现僵尸百分百因为之前制作组的原因停更了很久，不过在去年年底的时候复更了。想问下喵萌还有计划补完最后 3 集的字幕吗？感谢~

**Comment by MIRIMIRIM** [comment]
近期会更新完毕，现在已经更新了第10集。
