### ISSUE TITLE
芙莉莲E19错译反馈

### ISSUE THREAD

**Issue by Sakuratyann** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#70]
文件名：[Nekomoe kissaten][Sousou no Frieren][19][1080p][JPSC].mp4
时间点：00:01:58
此处翻译似乎与原意完全相反，正确意义应为“看吧，你能做到的”类似的肯定意思。
同时，使用谷歌翻译翻译此句"ほら やりゃできんだよ”之时，两句之间不带空格所翻译的中文刚好是贵组翻译的错误意义，似乎翻译人员在翻译时使用谷歌翻译错误导致此问题，希望贵组查证。
![e9fbb1198c1ec11ece9a0e9c25533146](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/157832779/78ec022d-81aa-4dc0-8afc-a4e54f7f8553)

**Comment by MIRIMIRIM** [comment]
感谢报错，会在合集中修正。

这里译错的原因是「ん在日语中根据语境可兼具肯定或否定的意思，所以校对时漏掉了」，当然 Google 翻译也是不存在的，机器翻译的文本会很容易被校对发现。
