### ISSUE TITLE
Maohgakuin II: About the current status

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#73]
Just want to ask: was this project really abandoned?

When this anime first came on air, you followed it and made subtitles for the first six episodes. Later, anime's producers announced the postponement, and after some time I noticed that the status of "Maohgakuin II" was changed to "Dead" in your project list. No further subtitles were produced after this.

I am not asking you to continue production, but as a follower of this anime and yours, I want to care about what's going on.

I'm sorry if my wording offended you, and you can just close this issue as not planned.

**Comment by MIRIMIRIM** [comment]
Asking about the status of the project is permitted.

After Maohgakuin II resume broadcasting, the proofreader no longer has time to complete the project. Unless a new proofreader takes over the project, but I can’t find anyone suitable at the moment.
