### ISSUE TITLE
Wiki: A Markdown format syntax was not applied correctly

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#74]
In this wiki: [ass_render_difference](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/wiki/ass_render_difference)

> 4. 部分字体的竖排效果，如 \fn@Source Han Sans
> 
> - 示例：[libass/issues/619](https://github.com/libass/libass/issues/619)
> - 错误：所有 VSFilter 系滤镜，应该是 GDI 的问题？目前无法解决
> - 正确：所有基于 libass 的字幕滤镜
> - 处理：~~以 libass 为准，~~libass 可能后续会改为和 VSFilter 同样的显示效果，但由于这个问题在 Windows 下难以解决，可能会考虑对 VSF 系渲染效果的兼容，同时在竖排时尽量避免如「思源」字体这类变化较大的字体 考虑制作一个转换 fs 的程序辅助

The correct effect should be:

> ~~以 libass 为准，~~

**Comment by MIRIMIRIM** [comment]
https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/wiki/ass_render_difference/28ddf8f428ad2c474b145d0edcef49d8d1e92e87
