### ISSUE TITLE
Summer_Ghost: Some problems with subtitles

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#75]
## FOR TEXT CONTENT
_[Nekomoe kissaten] Summer Ghost [Movie][BDRip].JPSC.ass_
_[Nekomoe kissaten] Summer Ghost [Movie][BDRip].JPTC.ass_
```
Dialogue: 1,0:02:40.23,0:02:41.06,Dial-CH,,0,0,0,,都到走这儿了？
Dialogue: 1,0:02:40.23,0:02:41.06,Dial-CH,,0,0,0,,都到走這裡了？
```
I think it should be:

> 都走到这儿了？
> 都走到這裡了？

```
Dialogue: 1,0:24:17.23,0:24:18.64,Dial-CH,,0,0,0,,所以才去寻找幽灵
Dialogue: 1,0:24:17.23,0:24:18.64,Dial-CH,,0,0,0,,所以才去尋找幽靈
```
(Optional) I think it would be better if added a “会”/“會”:

> 所以才会去寻找幽灵
> 所以才會去尋找幽靈

```
Dialogue: 1,0:24:22.83,0:24:26.15,Dial-CH,,0,0,0,,但是 他也一定有着自己烦恼吧
Dialogue: 1,0:24:22.83,0:24:26.15,Dial-CH,,0,0,0,,但是 他也一定有著自己煩惱吧
```
I suggest adding the word “的”:

> 但是 他也一定有着自己的烦恼吧
> 但是 他也一定有著自己的煩惱吧

## FOR TIMELINE

Starting at about 35:16, you will notice that there is a sound without subtitles. After a slight pause in the sound, the subtitles will reappear.

All three subtitle files have this problem.

---

Found these problems in this commit: https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Storage/commit/89d89223820e97a10af03dd67f58cfe57d6e16de
This problem also exists with subtitles in your BDRip.

I found other problems with your HEVC BDRip, but considering these aren’t strongly related to the subtitles themselves, I’ll mention them in another issue.

**Comment by MIRIMIRIM** [comment]
I will fix these later
