### ISSUE TITLE
Saijakutamer: fansub name in the filename header

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#81]
I noticed that when the MPEG-4 version was released the filename was:
```
[Nekomoe kisstan][Saijaku Tamer wa Gomi Hiroi no Tabi wo Hajimemashita][<ep>][<res>p][<JPSC/JPTC>].mp4
```
The header of the filename looks a little different.

> Nekomoe kiss<ins>tan</ins> (This project)
> Nekomoe kiss<ins>aten</ins> (Usually)

Not sure if this was intentional or a mistake. This change may cause issues when retrieving local files.

The version of HEVC Matroska released by LoliHouse seems to have no problem:
```
[Nekomoe kissaten&LoliHouse] Saijaku Tamer wa Gomi Hiroi no Tabi wo Hajimemashita - <ep> [WebRip 1080p HEVC-10bit AAC ASSx2].mkv
```

**Comment by MIRIMIRIM** [comment]
Thx, will fix.
