### ISSUE TITLE
Publish: duplicate description when released on Bangumi Moe

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#82]
_I have noticed this phenomenon for a long time, but recently I hesitated and decided to ask._

There appears to be a duplication of descriptions in some releases on _Bangumi Moe_ starting sometime in April 2023. This seems to have something to do with the publisher changing the way it is released. Similar phenomena were not found at several other sites, so I guess that might have something to do with _Bangumi Moe_ too.

I visit _Bangumi Moe_ from time to time, so don’t quite understand this phenomenon.

**Comment by MIRIMIRIM** [comment]
Thx, I didn't notice it before, but future releases will avoid it.
