### ISSUE TITLE
Wiki: some minor feedback

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#88]
## [Nekomoekissaten-SUB/Nekomoekissaten-Subs/wiki](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/wiki)

> libass 与 VSFilter渲染不一致的情况和推荐处理

Could you consider adding a space after _VSFilter_?

## [Nekomoekissaten-SUB/Nekomoekissaten-Storage/wiki](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Storage/wiki)

> 主要内容移动到 [喵萌奶茶屋 Wiki #字幕渲染](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/wiki#%E5%AD%97%E5%B9%95%E6%B8%B2%E6%9F%93=)，请移步观看。

The link should be edited to [Nekomoekissaten-SUB/Nekomoekissaten-Subs/wiki](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/wiki) or [Nekomoekissaten-SUB/Nekomoekissaten-Subs/wiki#render](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/wiki#render).

> [Wiki: 为什么改用libass (Nekomoekissaten-SUB/Nekomoekissaten-Storage)](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Storage/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E6%94%B9%E7%94%A8libass)

Could you consider moving to [Nekomoekissaten-SUB/Nekomoekissaten-Subs/wiki](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/wiki)?

**Comment by MIRIMIRIM** [comment]
I fixed the first two.
I am considering delete [Wiki: 为什么改用libass (Nekomoekissaten-SUB/Nekomoekissaten-Storage)](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Storage/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E6%94%B9%E7%94%A8libass), so I won’t move it.
