### ISSUE TITLE
Subtitles Storage: possibility for more subtitles from other producers to be uploaded to the repo

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#89]
I read carefully what was added in this commit: https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/commit/ed2c66b58f0e9180dc2e5b572b3dc7f62129db59.

But according to my observation, it seems that only subtitles whose subtitle producer is _MIR_ will be uploaded to the repo. Subtitles from other producers (such as _poi_, _天天王子_, _错党/錯黨_, etc.) seem to be only packaged and uploaded to https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Storage/releases/tag/subtitle_pkg, whether it has special effects or not.

My core question in this issue is there any plan to upload subtitles from other producers to the repo in the future? If the special effects are too large, is it possible to split them and upload them to the repo?

**Comment by MIRIMIRIM** [comment]
Mainly due to considerations about the size of subtitles, the versions without splitting exist because our workflows are different, and I don't have much energy to deal with them.

**Comment by MIRIMIRIM** [comment]
> @MIRIMIRIM
> 
> I understand. Then I will close this issue. I hope I can find a more appropriate way to contribute to this type of subtitles in the future.

Thx. I'm also considering if there is a better way to handle these subtitles.
