### ISSUE TITLE
Listener第三话英文歌词翻译不妥

### ISSUE THREAD

**Issue by iruletheworld** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#9]
Listener第三话约9分42秒出现的"It's better to burn out than to fade away"翻译不妥。

首先，我认为郝舫的翻译是错的。而且错得像个完全不懂英文的人。

"fade away"不是“苟且偷生”的意思。"fade away"也是要死的，不过是寂而无声的死。

其实这句还挺有意思的，因为"burn out"和“fade away”都是燃烧结束的方式，不过剧烈的程度有所不同。所以这里说的就是死亡的选择方式。这句另外有意思的地方是会令人想起"This is how the world ends, not with a bang but with a whimper"这一名句。虽然这里更加着重的是个人的终结，但个人自身的终结也是个人世界的终结。所以也可以引伸出Kuri反抗世界框条的精神。

另，此处的是"burn out"而不是“burnout”，两个词意思不同。后者指过劳。

故此，这句歌词比较贴切的中文译法，应该是“与其无疾而终，不如烈焰至尽” ，或是“与其无声消逝，不如暴焰至终”（暴，指猛烈），之类的。

**Comment by vxzms** [comment]
https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/commit/0e29eb821c624686ad06985ce580b682f9efb66c

**Comment by MIRIMIRIM** [comment]
https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/commit/0e29eb821c624686ad06985ce580b682f9efb66c
