### ISSUE TITLE
Publish: an extra space in the release description

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#90]
In the new release description currently in use:

> 奶茶屋所有最新的【[外挂字幕](https://github.com/Nekomoekissaten/Nekomoekissaten-Subs)】<ins> </ins>在这里，若想转载修改见 repo 的 README。

The underlined position is an extra space. This problem exists in releases with multiple projects and multiple producers.

I know this has minimal impact on the actual look and feel. In Chinese terms, it’s like _鸡蛋里挑骨头/雞蛋裡挑骨頭_. Hope you can forgive me.

**Comment by MIRIMIRIM** [comment]
OK, I will fix it. It seems that currently it only appears in nyaa.
