### ISSUE TITLE
Saijakutamer: feedback on LoliHouse Matroska releases

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#92]
When the video is played at the staff at the beginning of the first 6 episodes, the subtitles have some fallback font.

<details>
<summary>Details</summary>

![0](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-Subs/assets/158490944/5707800c-2e1f-4d12-9591-89dd96bb14f7)

</details>

mpv log:
```
[sub/ass] fontselect: Using default font family: (FOT-ModeMinALarge Std D, 400, 0) -> ArialMT, 0, ArialMT
```

There is no problem with MPEG-4 releases.

**Comment by MIRIMIRIM** [comment]
It looks like an [AFS ](https://github.com/tastysugar/AssFontSubset) bug, will check it later.

**Comment by MIRIMIRIM** [comment]
> @MIRIMIRIM
> 
> Until the issues with AFS are fixed, can the persons responsible for this project be advised to take additional steps to manually repair the subtitle files?
> 
> For example, use the `/fn` tag to specify the font, or editing manually the `jpup` style font after using AFS?

After discussion, we have decided to modify the subtitles to avoid this problem, and AFS currently does not have a plan to fix assparser.
