### ISSUE TITLE
Publish: link to GitHub in release description

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#95]
_Discovered by accident._

In the release description, the link to this GitHub repo seems to have been [Nekomoekissaten/Nekomoekissaten-Subs](https://github.com/Nekomoekissaten/Nekomoekissaten-Subs), but the organization name in the middle of the link seems to be the name from a few years ago - the name of the organization that I remember always seemed to be [Nekomoekissaten-SUB](https://github.com/Nekomoekissaten-SUB).

Although GitHub does the redirection, could you fix it if you have the chance? Accessing an existing link directly seems to be faster than redirecting.

**Comment by MIRIMIRIM** [comment]
I haven’t noticed this issue yet. The release pulish description will be updated later.
