### ISSUE TITLE
Bocchi_the_Rock: plan for web -> bd

### ISSUE THREAD

**Issue by 3gf8jv4dv** [Nekomoekissaten-SUB/Nekomoekissaten-Subs#98]
I watched it again using VCB-Studio’s BDRip with your subtitles and didn’t see any breaking changes in the Blu-ray compared to the web version.

A few minor flaws have been discovered and I have been created a pull request to address them.

**Comment by MIRIMIRIM** [comment]
> @MIRIMIRIM
> 
> Excuse me. I think there are no other big problem at the moment. If you have a chance, could you review these two?

OK, I will review these late. In my memory, there are many issues with *Bocchi the Rock*, and it will take some time to find them.
